from pathlib import Path
import re
import html as html_lib
import json
import webbrowser
from datetime import datetime
from urllib.parse import quote, unquote, parse_qs

import pandas as pd
import plotly.express as px
from dash import Dash, dcc, html, dash_table, Input, Output, State, no_update
import dash_bootstrap_components as dbc

# ============================================================
# CLIMATE CHANGE / FAO INTERVIEW DASHBOARD APP
# ============================================================
# Put this file in the same folder that contains your generated output folders,
# for example:
# C:/Users/User/PycharmProjects/UNESCO_BIRKETS/
#
# Install if needed:
# pip install dash dash-bootstrap-components pandas plotly
#
# Run:
# python climate_risk_interview_app.py
#
# Then open:
# http://127.0.0.1:8050
# ============================================================

APP_TITLE = "Lebanon Climate Risk & Adaptation Analytics"
APP_SUBTITLE = "Climate risk, vulnerability, adaptation and climate-smart agriculture screening dashboard"
APP_YEAR = "2024"
AUTHOR_NAME = "Simon Tanios"
INTERVIEW_ROLE = "Climate Change Specialist with FAO"
PREPARED_MESSAGE = (
    "Developed by Simon Tanios in preparation for the job interview as "
    "Climate Change Specialist with FAO. This dashboard demonstrates a rapid, "
    "reproducible geospatial workflow for climate risk assessment, vulnerability "
    "screening, adaptation planning and climate-smart agriculture prioritization."
)

BASE_DIR = Path(__file__).resolve().parent

# Folders generated by your Google Earth Engine / Folium scripts.
# The app now searches only these known folders plus other Lebanon/climate folders,
# and explicitly excludes unrelated folders such as output_water_detection.
KNOWN_OUTPUT_FOLDERS = [
    "lebanon_climate_hazard_maps_2024",
    "lebanon_vegetation_stress_maps_2024",
    "lebanon_heat_stress_maps_2024",
    "lebanon_cropland_drought_exposure_2024",
    "lebanon_composite_agriculture_climate_risk_2024",
    "lebanon_erosion_runoff_susceptibility_2024",
    "lebanon_evapotranspiration_water_stress_2024",
    "lebanon_three_priority_analyses_2024",
    "lebanon_four_advanced_climate_risk_analyses_2024",
    "lebanon_future_climate_projections_cmip6",
]

EXCLUDED_FOLDERS = {
    "output_water_detection",
    "water_detection",
    "output_waterdetect",
    "output_water_detect",
    "cache",
    "OWM_cache",
    ".idea",
    "__pycache__",
    "assets",
    "venv",
    "env",
}

# Preferred dashboard / decision-support files to highlight on the home page.
FEATURED_PATTERNS = [
    "*drought*hazard*dashboard*.html",
    "*vegetation*stress*dashboard*.html",
    "*cropland*drought*exposure*dashboard*.html",
    "*agriculture*climate*risk*dashboard*.html",
    "*erosion*runoff*dashboard*.html",
    "*et*water*demand*dashboard*.html",
    "*vci*agricultural*drought*dashboard*.html",
    "*irrigation*priority*dashboard*.html",
    "*flood*exposure*dashboard*.html",
    "*watershed*nbs*dashboard*.html",
    "*csa*intervention*dashboard*.html",
    "*multi*hazard*vulnerability*dashboard*.html",
    "*projection*dashboard*.html",
]

METHODOLOGY_CARDS = [
    {
        "title": "1. Climate hazard screening",
        "text": "CHIRPS rainfall was used to compare 2024 annual rainfall against a 1991–2020 baseline. Rainfall deficit was classified into drought hazard classes.",
        "tags": ["CHIRPS", "Drought", "Rainfall anomaly"]
    },
    {
        "title": "2. Vegetation and agricultural drought",
        "text": "MODIS NDVI was used to assess vegetation stress and calculate VCI, a remote-sensing agricultural drought indicator.",
        "tags": ["MODIS NDVI", "VCI", "Vegetation stress"]
    },
    {
        "title": "3. Water demand and heat stress",
        "text": "MODIS ET and land surface temperature were used to screen potential water-demand stress and surface heat-stress patterns.",
        "tags": ["Evapotranspiration", "LST", "Water demand"]
    },
    {
        "title": "4. Exposure and vulnerability",
        "text": "ESA WorldCover cropland and built-up layers were overlaid with hazard layers to identify agricultural and infrastructure exposure.",
        "tags": ["Cropland", "Built-up", "Exposure"]
    },
    {
        "title": "5. Adaptation prioritization",
        "text": "Composite indices identify climate-smart agriculture options such as drip irrigation, drought-tolerant crops, soil conservation, agroforestry and nature-based solutions.",
        "tags": ["CSA", "Irrigation", "NbS"]
    },
    {
        "title": "6. Future climate projections",
        "text": "NASA GDDP-CMIP6 outputs were used to compare future SSP2-4.5 and SSP5-8.5 scenarios against a 1995–2014 baseline.",
        "tags": ["CMIP6", "SSP2-4.5", "SSP5-8.5"]
    },
]

REPORT_TEXT = """
This application presents a rapid, reproducible geospatial screening workflow for Lebanon, developed to demonstrate practical capacity in climate risk and vulnerability assessment, remote sensing, adaptation planning and decision-support mapping.

The workflow combines open datasets including CHIRPS rainfall, MODIS NDVI, MODIS evapotranspiration, MODIS land surface temperature, SRTM elevation, ESA WorldCover and NASA GDDP-CMIP6 projections. The outputs are intended as screening layers for programme design and field validation, not as final engineering or national hydrological modelling products.

The analysis moves from climate hazards to exposure and prioritization: rainfall deficit and drought hazard, vegetation stress, water-demand stress, flood susceptibility, cropland exposure, watershed and runoff risk, climate-smart agriculture suitability, multi-hazard vulnerability and future climate stress under SSP scenarios.
"""

CAVEAT_TEXT = """
Important interpretation note: these maps are rapid screening outputs. Thresholds and weights are transparent and adjustable, which makes the workflow suitable for adaptation planning discussions and further refinement with government or FAO technical teams.
"""

# ============================================================
# FILE DISCOVERY
# ============================================================

def is_excluded_path(path: Path) -> bool:
    parts = {p.lower() for p in path.parts}
    excluded = {x.lower() for x in EXCLUDED_FOLDERS}
    if parts.intersection(excluded):
        return True
    path_text = str(path).lower()
    if "output_water_detection" in path_text:
        return True
    return False


def clean_name(path_or_name):
    name = Path(path_or_name).stem if isinstance(path_or_name, (str, Path)) else str(path_or_name)
    name = re.sub(r"[_\-]+", " ", name)
    name = re.sub(r"\bmap\b", "Map", name, flags=re.IGNORECASE)
    name = re.sub(r"\bssp245\b", "SSP2-4.5", name, flags=re.IGNORECASE)
    name = re.sub(r"\bssp585\b", "SSP5-8.5", name, flags=re.IGNORECASE)
    name = re.sub(r"\s+", " ", name).strip()
    return name.title()


def infer_theme(path: Path) -> str:
    full = str(path).lower()
    if "future" in full or "cmip6" in full or "ssp" in full or "projection" in full:
        return "Future climate projections"
    if "multi" in full and "vulnerability" in full:
        return "Multi-hazard vulnerability"
    if "csa" in full or "intervention" in full or "agroforestry" in full or "drip" in full:
        return "Climate-smart agriculture"
    if "watershed" in full or "nbs" in full or "upstream" in full:
        return "Watershed and nature-based solutions"
    if "flood" in full:
        return "Flood exposure"
    if "irrigation" in full:
        return "Irrigation priority"
    if "vci" in full:
        return "Agricultural drought / VCI"
    if "rainfall_seasonality" in full or "dry_season" in full or "monthly_rainfall" in full:
        return "Water availability and rainfall seasonality"
    if "evapotranspiration" in full or "et_water" in full or "water_demand" in full:
        return "Evapotranspiration and water demand"
    if "erosion" in full or "runoff" in full:
        return "Erosion and runoff susceptibility"
    if "composite" in full and "agriculture" in full:
        return "Composite agricultural climate risk"
    if "cropland" in full and "drought" in full:
        return "Cropland exposure to drought"
    if "vegetation" in full or "ndvi" in full:
        return "Vegetation stress"
    if "heat" in full or "lst" in full:
        return "Heat stress"
    if "drought" in full or "hazard" in full or "rainfall" in full:
        return "Drought and rainfall hazard"
    return "Other climate outputs"


def discover_output_roots():
    roots = []

    # 1) Prefer the known folders from your climate-risk work.
    for folder in KNOWN_OUTPUT_FOLDERS:
        p = BASE_DIR / folder
        if p.exists() and p.is_dir() and not is_excluded_path(p):
            roots.append(p)

    # 2) Auto-detect additional relevant climate/Lebanon folders, but exclude unrelated folders.
    allowed_keywords = ["lebanon", "climate", "drought", "risk", "hazard", "irrigation", "flood", "cmip6", "vegetation", "erosion", "runoff", "evapotranspiration"]
    for p in BASE_DIR.iterdir():
        if not p.is_dir():
            continue
        if is_excluded_path(p):
            continue
        lower_name = p.name.lower()
        if not any(k in lower_name for k in allowed_keywords):
            continue
        has_outputs = any(p.rglob("*.html")) or any(p.rglob("*.csv")) or any(p.rglob("*.xlsx")) or any(p.rglob("*.png"))
        if has_outputs and p not in roots:
            roots.append(p)

    return sorted(roots, key=lambda x: x.name.lower())


def discover_files():
    roots = discover_output_roots()
    records = []
    for root in roots:
        for pattern in ("*.html", "*.csv", "*.xlsx", "*.png", "*.jpg", "*.jpeg"):
            for f in root.rglob(pattern):
                if f.name.startswith("~$") or is_excluded_path(f):
                    continue
                rel = f.relative_to(BASE_DIR)
                records.append({
                    "path": f,
                    "relative_path": str(rel).replace("\\", "/"),
                    "name": clean_name(f.name),
                    "file_name": f.name,
                    "folder": root.name,
                    "theme": infer_theme(f),
                    "suffix": f.suffix.lower(),
                    "modified": datetime.fromtimestamp(f.stat().st_mtime).strftime("%Y-%m-%d %H:%M"),
                    "size_kb": round(f.stat().st_size / 1024, 1),
                })
    return records


FILES = discover_files()
MAP_FILES = [r for r in FILES if r["suffix"] == ".html"]
TABLE_FILES = [r for r in FILES if r["suffix"] in {".csv", ".xlsx"}]
IMAGE_FILES = [r for r in FILES if r["suffix"] in {".png", ".jpg", ".jpeg"}]


def file_options(records):
    grouped = sorted(records, key=lambda r: (r["theme"], r["folder"], r["file_name"]))
    return [
        {
            "label": f"{r['theme']} | {r['name']}",
            "value": r["relative_path"]
        }
        for r in grouped
    ]


def get_record(relative_path):
    if not relative_path:
        return None
    relative_path = str(relative_path).replace("\\", "/")
    for r in FILES:
        if r["relative_path"] == relative_path:
            return r
    return None


def find_featured_maps():
    featured = []
    seen = set()
    roots = discover_output_roots()
    for pattern in FEATURED_PATTERNS:
        for root in roots:
            for f in root.rglob(pattern):
                if is_excluded_path(f):
                    continue
                rel = str(f.relative_to(BASE_DIR)).replace("\\", "/")
                if rel in seen:
                    continue
                rec = get_record(rel)
                if rec:
                    featured.append(rec)
                    seen.add(rel)
    if not featured:
        featured = MAP_FILES[:8]
    return featured[:16]


FEATURED_MAPS = find_featured_maps()

# ============================================================
# DATA LOADING
# ============================================================

def safe_read_table(path: Path) -> pd.DataFrame:
    try:
        if path.suffix.lower() == ".csv":
            return pd.read_csv(path)
        if path.suffix.lower() == ".xlsx":
            return pd.read_excel(path)
    except Exception as e:
        return pd.DataFrame({"error": [str(e)]})
    return pd.DataFrame()


def dataframe_preview(df: pd.DataFrame, max_rows=500):
    if df.empty:
        return pd.DataFrame({"message": ["No data available"]})
    return df.head(max_rows).copy()


def make_table_component(df: pd.DataFrame, page_size=12):
    if df.empty:
        return dbc.Alert("No rows found in this file.", color="warning")

    display_df = dataframe_preview(df, 500)
    return dash_table.DataTable(
        data=display_df.to_dict("records"),
        columns=[{"name": str(c), "id": str(c)} for c in display_df.columns],
        page_size=page_size,
        filter_action="native",
        sort_action="native",
        export_format="csv",
        style_table={"overflowX": "auto", "maxHeight": "520px", "overflowY": "auto"},
        style_cell={
            "fontFamily": "Arial",
            "fontSize": "13px",
            "textAlign": "left",
            "padding": "8px",
            "whiteSpace": "normal",
            "height": "auto",
            "minWidth": "120px",
            "maxWidth": "360px",
        },
        style_header={"fontWeight": "bold", "backgroundColor": "#eef2f7"},
    )


def infer_numeric_columns(df: pd.DataFrame):
    numeric_cols = []
    for c in df.columns:
        s = pd.to_numeric(df[c], errors="coerce")
        if s.notna().sum() >= max(1, min(5, len(df) // 5)):
            numeric_cols.append(c)
    return numeric_cols


def infer_label_columns(df: pd.DataFrame):
    preferred = [
        "class_label", "hazard_label", "risk_label", "recommended_intervention",
        "scenario", "period", "month", "HYBAS_ID", "flood_class",
        "vulnerability_class", "irrigation_priority_class", "csa_code",
        "climate_stress_class", "et_stress_class", "vci_drought_class"
    ]
    labels = [c for c in preferred if c in df.columns]
    labels += [c for c in df.columns if df[c].dtype == "object" and c not in labels]
    labels += [c for c in df.columns if c not in labels]
    return labels


def build_chart(df: pd.DataFrame, selected_x=None, selected_y=None):
    if df.empty or len(df.columns) < 2:
        return html.Div()

    numeric_cols = infer_numeric_columns(df)
    label_cols = infer_label_columns(df)
    if not numeric_cols:
        return dbc.Alert("No numeric column detected for charting.", color="secondary")

    x_col = selected_x if selected_x in df.columns else label_cols[0]
    y_col = selected_y if selected_y in df.columns else numeric_cols[0]

    tmp = df.copy()
    tmp[y_col] = pd.to_numeric(tmp[y_col], errors="coerce")
    tmp = tmp.dropna(subset=[y_col]).head(100)

    if tmp.empty:
        return dbc.Alert("No numeric rows available for the selected chart.", color="secondary")

    fig = px.bar(
        tmp,
        x=x_col,
        y=y_col,
        title=f"{y_col} by {x_col}",
        template="plotly_white"
    )
    fig.update_layout(margin=dict(l=30, r=20, t=60, b=80), height=420)
    return dcc.Graph(figure=fig, config={"displaylogo": False})


def read_html_map(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except Exception as e:
        return f"<h3>Could not read map</h3><p>{html_lib.escape(str(e))}</p>"


# ============================================================
# REUSABLE UI COMPONENTS
# ============================================================

def prepared_banner(section_name="this section"):
    return dbc.Alert(
        [
            html.Strong("Prepared by Simon Tanios. "),
            html.Span(
                "This application was developed in preparation for the job interview as Climate Change Specialist with FAO Lebanon. "
                "It demonstrates relevant work related to the role, including applied climate-risk analytics, geospatial screening, "
                "adaptation-oriented analysis, and decision-support tools for nature-based solutions and related climate-resilience interventions."
            ),
        ],
        color="info",
        className="shadow-sm border-0 mt-3 mb-3",
    )


def stat_card(label, value, color="primary"):
    return dbc.Card(
        dbc.CardBody([
            html.Div(label, className="text-muted", style={"fontSize": "13px"}),
            html.H3(value, className=f"text-{color} mb-0")
        ]),
        className="shadow-sm border-0 h-100"
    )


def methodology_card(item):
    return dbc.Card(
        dbc.CardBody([
            html.H5(item["title"], className="mb-2"),
            html.P(item["text"], className="text-muted"),
            html.Div([dbc.Badge(t, color="secondary", className="me-1 mb-1") for t in item["tags"]])
        ]),
        className="shadow-sm border-0 h-100"
    )


def map_link(relative_path):
    return f"/?tab=tab-maps&map={quote(relative_path)}"


def map_card(rec):
    return dbc.Card(
        dbc.CardBody([
            html.H6(rec["name"], className="mb-1"),
            html.Div(rec["theme"], className="text-muted small mb-2"),
            dbc.Button(
                "Open in Map Viewer",
                href=map_link(rec["relative_path"]),
                color="primary",
                size="sm",
                external_link=False,
            )
        ]),
        className="shadow-sm border-0 h-100"
    )


# ============================================================
# APP LAYOUT
# ============================================================

external_stylesheets = [dbc.themes.BOOTSTRAP]
app = Dash(__name__, external_stylesheets=external_stylesheets, suppress_callback_exceptions=True)
server = app.server

NAVBAR = dbc.Navbar(
    dbc.Container([
        dbc.Row([
            dbc.Col(html.Div("🌍", style={"fontSize": "30px"}), width="auto"),
            dbc.Col([
                html.Div(APP_TITLE, className="fw-bold", style={"fontSize": "20px"}),
                html.Div(APP_SUBTITLE, style={"fontSize": "13px", "opacity": 0.85}),
            ])
        ], align="center", className="g-2"),
        dbc.Badge("Developed by Simon Tanios | FAO interview preparation", color="light", text_color="dark", className="ms-auto")
    ], fluid=True),
    color="dark",
    dark=True,
    sticky="top",
)

home_tab = html.Div([
    prepared_banner("overview page"),

    dbc.Row([
        dbc.Col(stat_card("HTML map outputs detected", str(len(MAP_FILES)), "success"), md=3),
        dbc.Col(stat_card("CSV / Excel result tables", str(len(TABLE_FILES)), "info"), md=3),
        dbc.Col(stat_card("Figures / images", str(len(IMAGE_FILES)), "warning"), md=3),
        dbc.Col(stat_card("Themes detected", str(len(sorted(set(r['theme'] for r in FILES)))), "danger"), md=3),
    ], className="g-3 mb-4"),

    dbc.Row([
        dbc.Col([
            dbc.Card(dbc.CardBody([
                html.H4("Purpose of this app"),
                dcc.Markdown(REPORT_TEXT),
                dbc.Alert(CAVEAT_TEXT, color="warning", className="mt-3"),
                html.Hr(),
                html.H6("Most relevant outputs"),
                html.Ul([
                    html.Li("Drought and rainfall deficit hazard"),
                    html.Li("Cropland exposure and irrigation priority"),
                    html.Li("Climate-smart agriculture intervention suitability"),
                    html.Li("Multi-hazard vulnerability and future climate projections"),
                ])
            ]), className="shadow-sm border-0")
        ], width=12),
    ], className="g-3 mb-4"),

    html.H4("Featured dashboards and maps", className="mb-3"),
    dbc.Row([dbc.Col(map_card(rec), md=4, lg=3, className="mb-3") for rec in FEATURED_MAPS], className="g-3"),

    html.H4("Methodological workflow", className="mt-4 mb-3"),
    dbc.Row([dbc.Col(methodology_card(item), md=6, lg=4, className="mb-3") for item in METHODOLOGY_CARDS], className="g-3"),
])

map_viewer_tab = html.Div([
    prepared_banner("map viewer"),

    dbc.Card(dbc.CardBody([
        dbc.Row([
            dbc.Col([
                html.Label("Filter by theme", className="fw-bold"),
                dcc.Dropdown(
                    id="theme-filter",
                    options=[{"label": t, "value": t} for t in sorted(set(r["theme"] for r in MAP_FILES))],
                    multi=True,
                    placeholder="All themes"
                ),
            ], md=4),
            dbc.Col([
                html.Label("Select map", className="fw-bold"),
                dcc.Dropdown(
                    id="map-select",
                    options=file_options(MAP_FILES),
                    value=FEATURED_MAPS[0]["relative_path"] if FEATURED_MAPS else (MAP_FILES[0]["relative_path"] if MAP_FILES else None),
                    placeholder="Choose an HTML map"
                ),
            ], md=8),
        ], className="g-3"),
    ]), className="shadow-sm border-0 mb-3"),

    dbc.Row([
        dbc.Col([
            dbc.Card(dbc.CardBody([
                html.Div(id="map-metadata", className="mb-2"),
                html.Iframe(
                    id="map-frame",
                    srcDoc="<h3>No map selected</h3>",
                    style={"width": "100%", "height": "760px", "border": "1px solid #ddd", "borderRadius": "8px"},
                )
            ]), className="shadow-sm border-0")
        ], width=12)
    ])
])

results_tab = html.Div([
    prepared_banner("results table section"),

    dbc.Card(dbc.CardBody([
        dbc.Row([
            dbc.Col([
                html.Label("Select results table", className="fw-bold"),
                dcc.Dropdown(
                    id="table-select",
                    options=file_options(TABLE_FILES),
                    value=TABLE_FILES[0]["relative_path"] if TABLE_FILES else None,
                    placeholder="Choose a CSV/Excel file"
                ),
            ], md=8),
            dbc.Col([
                html.Label("Quick filter", className="fw-bold"),
                dbc.Input(id="table-search", placeholder="Search in loaded table...", type="text"),
            ], md=4),
        ], className="g-3"),
    ]), className="shadow-sm border-0 mb-3"),

    dbc.Row([
        dbc.Col(dbc.Card(dbc.CardBody(html.Div(id="table-metadata")), className="shadow-sm border-0 mb-3"), width=12),
    ]),

    dbc.Row([
        dbc.Col([
            dbc.Card(dbc.CardBody([
                html.H5("Data table"),
                html.Div(id="table-output")
            ]), className="shadow-sm border-0")
        ], lg=7),
        dbc.Col([
            dbc.Card(dbc.CardBody([
                html.H5("Quick chart"),
                dbc.Row([
                    dbc.Col([html.Label("X"), dcc.Dropdown(id="chart-x")], md=6),
                    dbc.Col([html.Label("Y"), dcc.Dropdown(id="chart-y")], md=6),
                ], className="g-2 mb-3"),
                html.Div(id="chart-output")
            ]), className="shadow-sm border-0")
        ], lg=5),
    ], className="g-3"),
])

figures_tab = html.Div([
    prepared_banner("figures and charts section"),

    dbc.Card(dbc.CardBody([
        html.Label("Select figure / image", className="fw-bold"),
        dcc.Dropdown(
            id="image-select",
            options=file_options(IMAGE_FILES),
            value=IMAGE_FILES[0]["relative_path"] if IMAGE_FILES else None,
            placeholder="Choose an image"
        ),
    ]), className="shadow-sm border-0 mb-3"),
    dbc.Card(dbc.CardBody(html.Div(id="image-output")), className="shadow-sm border-0")
])

files_tab = html.Div([
    prepared_banner("output inventory"),

    dbc.Card(dbc.CardBody([
        html.H4("All detected climate-risk outputs"),
        html.P("This inventory helps you check what the app found in your climate-risk project folders. The unrelated output_water_detection folder is intentionally excluded."),
        dash_table.DataTable(
            data=[{k: v for k, v in r.items() if k != "path"} for r in FILES],
            columns=[{"name": c, "id": c} for c in ["theme", "folder", "file_name", "suffix", "modified", "size_kb", "relative_path"]],
            page_size=20,
            filter_action="native",
            sort_action="native",
            export_format="csv",
            style_table={"overflowX": "auto"},
            style_cell={"fontFamily": "Arial", "fontSize": "13px", "textAlign": "left", "padding": "8px"},
            style_header={"fontWeight": "bold", "backgroundColor": "#eef2f7"},
        )
    ]), className="shadow-sm border-0")
])

app.layout = html.Div([
    dcc.Location(id="url", refresh=False),
    NAVBAR,
    dbc.Container([
        dbc.Tabs([
            dbc.Tab(home_tab, label="Overview", tab_id="tab-home"),
            dbc.Tab(map_viewer_tab, label="Map viewer", tab_id="tab-maps"),
            dbc.Tab(results_tab, label="Results tables", tab_id="tab-results"),
            dbc.Tab(figures_tab, label="Charts / figures", tab_id="tab-figures"),
            dbc.Tab(files_tab, label="Output inventory", tab_id="tab-files"),
        ], id="main-tabs", active_tab="tab-home", className="mt-3"),
        html.Footer(
            html.Div([
                html.Hr(),
                html.Small(
                    "Developed by Simon Tanios in preparation for the FAO Climate Change Specialist interview. Built with Python, Google Earth Engine outputs, Folium, Dash and Plotly.",
                    className="text-muted"
                )
            ]),
            className="my-4"
        )
    ], fluid=True),
])

# ============================================================
# CALLBACKS
# ============================================================

@app.callback(
    Output("main-tabs", "active_tab"),
    Output("map-select", "value"),
    Input("url", "search"),
    State("map-select", "value"),
)
def route_from_url(search, current_map):
    if not search:
        return "tab-home", current_map

    params = parse_qs(search.lstrip("?"))
    tab = params.get("tab", ["tab-home"])[0]
    selected_map = params.get("map", [current_map])[0]
    selected_map = unquote(selected_map) if selected_map else current_map

    valid_tabs = {"tab-home", "tab-maps", "tab-results", "tab-figures", "tab-files"}
    if tab not in valid_tabs:
        tab = "tab-home"

    if selected_map and not get_record(selected_map):
        selected_map = current_map

    return tab, selected_map


@app.callback(
    Output("map-select", "options"),
    Input("theme-filter", "value"),
)
def update_map_options(themes):
    records = MAP_FILES
    if themes:
        records = [r for r in MAP_FILES if r["theme"] in themes]
    return file_options(records)


@app.callback(
    Output("map-frame", "srcDoc"),
    Output("map-metadata", "children"),
    Input("map-select", "value"),
)
def load_map(relative_path):
    if not relative_path:
        return "<h3>No map selected</h3>", dbc.Alert("No HTML maps were found. Check that the app is in the same folder as your output folders.", color="warning")

    rec = get_record(relative_path)
    if not rec:
        return "<h3>Map not found</h3>", dbc.Alert("Selected map not found.", color="danger")

    src_doc = read_html_map(rec["path"])
    meta = dbc.Row([
        dbc.Col(dbc.Badge(rec["theme"], color="primary"), width="auto"),
        dbc.Col(html.Strong(rec["name"]), width="auto"),
        dbc.Col(html.Span(rec["relative_path"], className="text-muted small"), width="auto"),
    ], align="center", className="g-2")
    return src_doc, meta


@app.callback(
    Output("table-output", "children"),
    Output("table-metadata", "children"),
    Output("chart-x", "options"),
    Output("chart-y", "options"),
    Output("chart-x", "value"),
    Output("chart-y", "value"),
    Input("table-select", "value"),
    Input("table-search", "value"),
)
def load_table(relative_path, search_text):
    if not relative_path:
        return dbc.Alert("No CSV/Excel tables were found.", color="warning"), "", [], [], None, None

    rec = get_record(relative_path)
    if not rec:
        return dbc.Alert("Selected table not found.", color="danger"), "", [], [], None, None

    df = safe_read_table(rec["path"])

    if search_text and not df.empty:
        mask = pd.Series(False, index=df.index)
        for col in df.columns:
            mask = mask | df[col].astype(str).str.contains(search_text, case=False, na=False)
        df = df[mask]

    numeric_cols = infer_numeric_columns(df)
    label_cols = infer_label_columns(df)
    all_options = [{"label": str(c), "value": str(c)} for c in df.columns]
    num_options = [{"label": str(c), "value": str(c)} for c in numeric_cols]

    x_value = label_cols[0] if label_cols else (df.columns[0] if len(df.columns) else None)
    y_value = numeric_cols[0] if numeric_cols else None

    metadata = html.Div([
        dbc.Badge(rec["theme"], color="primary", className="me-2"),
        html.Strong(rec["name"]),
        html.Div(f"{rec['relative_path']} | {len(df):,} rows | {len(df.columns):,} columns", className="text-muted small mt-1")
    ])

    return make_table_component(df), metadata, all_options, num_options, x_value, y_value


@app.callback(
    Output("chart-output", "children"),
    Input("table-select", "value"),
    Input("table-search", "value"),
    Input("chart-x", "value"),
    Input("chart-y", "value"),
)
def update_chart(relative_path, search_text, x_col, y_col):
    if not relative_path:
        return dbc.Alert("Select a table to create a chart.", color="secondary")
    rec = get_record(relative_path)
    if not rec:
        return dbc.Alert("Selected table not found.", color="danger")
    df = safe_read_table(rec["path"])
    if search_text and not df.empty:
        mask = pd.Series(False, index=df.index)
        for col in df.columns:
            mask = mask | df[col].astype(str).str.contains(search_text, case=False, na=False)
        df = df[mask]
    return build_chart(df, x_col, y_col)


@app.callback(
    Output("image-output", "children"),
    Input("image-select", "value"),
)
def load_image(relative_path):
    if not relative_path:
        return dbc.Alert("No figures/images were found.", color="warning")
    rec = get_record(relative_path)
    if not rec:
        return dbc.Alert("Selected image not found.", color="danger")

    import base64
    mime = "image/png" if rec["suffix"] == ".png" else "image/jpeg"
    data = base64.b64encode(rec["path"].read_bytes()).decode("ascii")
    src = f"data:{mime};base64,{data}"

    return html.Div([
        html.Div([
            dbc.Badge(rec["theme"], color="primary", className="me-2"),
            html.Strong(rec["name"]),
            html.Div(rec["relative_path"], className="text-muted small mt-1")
        ], className="mb-3"),
        html.Img(src=src, style={"maxWidth": "100%", "border": "1px solid #ddd", "borderRadius": "8px"})
    ])

# ============================================================
# RUN SERVER
# ============================================================

if __name__ == "__main__":
    print("-------------------------------------------------------")
    print(APP_TITLE)
    print("-------------------------------------------------------")
    print(f"Base folder: {BASE_DIR}")
    print(f"Maps detected: {len(MAP_FILES)}")
    print(f"Tables detected: {len(TABLE_FILES)}")
    print(f"Images detected: {len(IMAGE_FILES)}")
    print("Excluded folders:", ", ".join(sorted(EXCLUDED_FOLDERS)))
    print("Open: http://127.0.0.1:8050")
    print("-------------------------------------------------------")
    webbrowser.open("http://127.0.0.1:8050")
    app.run(debug=True, host="127.0.0.1", port=8050)
